name: Sign Of The Day Scrapper

on:
  schedule:
    - cron: "0 21 * * *"  # Runs daily at 21:00 UTC

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2  # Checkout the repository content to github runner

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests beautifulsoup4 python-dotenv

      - name: Set up secret as environment variable
        env:
          DISCORD_WEBHOOK_SIGN_OF_THE_DAY: ${{ secrets.DISCORD_WEBHOOK_SIGN_OF_THE_DAY }}  # Pass secret to the environment
        run: |
          echo "DISCORD_WEBHOOK_SIGN_OF_THE_DAY=${{ secrets.DISCORD_WEBHOOK_SIGN_OF_THE_DAY }}" >> $GITHUB_ENV

      - name: Execute Sign Of The Day Scraper
        run: python sign_of_the_day_scraper.py
